### PR TITLE
fix: correct parse inline directive without content and dests

### LINKED ISSUE #5: [Bug] Runtime error when parsing inline directive
Runtime error occurs when parsing this markup:

```md
[aa:aa](aa.com)

[xx]: bb.com
```

Error occurs inside `normalizeReference()` inside `parseDirective()` function

> TypeError: Cannot read properties of undefined (reading 'trim')

If you disable the inline directives, then there is no error

```js
md.inline.ruler.disable('inline_directive');
```

### PR DESCRIPTION
**Pull request by d3m1d0v**
Fixed #5

### CODE REVIEW

**Comment by d3m1d0v** [comment]
@hilookas plz look at this PR
This is an important fix for us

**Review by makhnatkin — APPROVED** [review]
Great job!

**Comment by hilookas** [comment]
Thanks for your contribution!

**Comment by d3m1d0v** [comment]
@hilookas
can u publish this update? plz
we are waiting for this fix :)

**Comment by hilookas** [comment]
> @hilookas can u publish this update? plz we are waiting for this fix :)

Sure! I have published this to npmjs. :D

**Pull request merged**
